name: Pull Request Check

on:
  pull_request:
    branches:
      - master
      - '*.x.x'
    paths-ignore:
      - 'website/**'
      - '*.md'

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Set up Gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Used by maven-plugin integration tests
      - name: Set up Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build library with Gradle
        run: |
          ./gradlew clean build
          find -name \*.jar

      - name: archive built JAR for graphql-kotlin-spring-server
        uses: actions/upload-artifact@v2
        with:
          name: graphql-kotlin-spring-server
          path: |
            ./plugins/graphql-kotlin-maven-plugin/build/local-repo/com/expediagroup/graphql-kotlin-spring-server/6.0.0-SNAPSHOT/graphql-kotlin-spring-server-6.0.0-SNAPSHOT.jar
            ./servers/graphql-kotlin-spring-server/build/libs/graphql-kotlin-spring-server-6.0.0-SNAPSHOT.jar
          retention-days: 7

      - name: Archive failure build reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-reports
          path: |
            ./**/build/reports
            plugins/graphql-kotlin-maven-plugin/build/integration/**/build.log
            plugins/graphql-kotlin-maven-plugin/build/integration/**/target/surefire-reports
          retention-days: 7

      - name: Build examples with Gradle
        working-directory: examples
        run: ./gradlew clean build

      - name: Archive examples failure build reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-examples-reports
          path: ./examples/**/build/reports
          retention-days: 7
